services:
  - type: web
    name: sales-forecast-api
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: GOOGLE_API_KEY
        value: AIzaSyDXiL2KIckvagWgQq2aqTDfgxx-YkbND0w
